# Generated by Django 2.0.7 on 2020-01-08 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyManagerApp', '0003_auto_20200108_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='MoneyManagerApp.Account'),
        ),
    ]
