# Generated by Django 2.0.7 on 2020-01-10 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyManagerApp', '0005_auto_20200108_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('IL', 'Initial'), ('SY', 'Salary'), ('PN', 'Pension'), ('BS', 'Bonds'), ('DS', 'Dividends'), ('GT', 'Grant'), ('IT', 'Interest'), ('OF', 'Offer'), ('PE', 'Prize'), ('RD', 'Refund'), ('RL', 'Rental'), ('SE', 'Sale'), ('TR', 'Transfer'), ('OR', 'Other'), ('FD', 'Food'), ('HD', 'Household'), ('AL', 'Apparel'), ('CE', 'Culture'), ('EN', 'Education'), ('ES', 'Electronics'), ('HH', 'Health'), ('IT', 'Installment'), ('LN', 'Loan'), ('HY', 'Hobby'), ('TT', 'Transportation'), ('TR', 'Transfer'), ('OR', 'Other')], max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(max_length=25, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('O', 'Outcome')], max_length=1, verbose_name='Transaction type'),
        ),
    ]
